site_name: REMIND-MFA
nav: 
  - Home: index.md
  - Model overview: 
      - Scope: scope.md
      - Flodym: flodym.md
      - Methodology: methodology.md
      - Input data: input_data.md
  - Sub-modules:
      - Steel MFA: steel.md
      - Plastic MFA: plastic.md
      - Cement MFA: cement.md
  - References: references.md
theme: readthedocs
markdown_extensions:
  - markdown_include.include:
      base_path: docs