site_name: REMIND-MFA
nav:
  - Home: index.md
  - Model overview:
      - Scope: scope.md
      - Flodym: flodym.md
      - Code Structure: code_structure.md
      - Methodology: methodology.md
      - Input data: input_data.md
  - Sub-modules:
      - Steel MFA: steel.md
      - Plastic MFA: plastic.md
      - Cement MFA: cement.md
  - REMIND-MFA in TRANSIENCE:
      - Context: transience_context.md
      - Integration in MIC3: mic3_integration.md
theme: readthedocs
hooks:
  - docs/merge_bibtex_files.py
  - docs/merge_parameters_sources.py
plugins:
  - search
  - include-markdown
  - bibtex:
      bib_file: "docs/all_refs.bib"
      csl_file: "docs/apa.csl"
markdown_extensions:
  - footnotes
extra_css:
  - 'css/custom.css'
extra_javascript:
  - 'js/add_table_class.js'
