model: 'cement'

input:
  madrat_output_path: '../madrat_wd/output'
  force_extract_tgz: False
  input_data_path: '../remind_mfa_data/h12'
  input_data_version: 'rev0_h12_bbd76206_mfa'
  scenarios_path: 'config/scenarios'

model_switches:
  scenario: 'SSP2'
  mode: 'base' # can be "base", "carbon_flow"
  stock_extrapolation_class_name: 'LogisticExtrapolation'
  regress_over: loggdppc
  lifetime_model_name: 'LogNormalLifetime'
  parameter_extrapolation:
    clinker_ratio: 'ConstantExtrapolation'
    use_lifetime_mean: 'ConstantExtrapolation'
    cement_trade: 'ZeroExtrapolation'

visualization:
  do_visualize: True
  do_show_figs: True
  do_save_figs: False
  figures_path: 'data/cement/output/figures'
  plotting_engine: 'plotly'
  production:
    do_visualize: False
  consumption:
    do_visualize: True
  use_stock:
    do_visualize: True
    over_gdp: True
    per_capita: True
  eol_stock:
    do_visualize: True
    over_gdp: False
    per_capita: False
  prod_clinker:
    do_visualize: False
  prod_cement:
    do_visualize: True
  prod_product:
    do_visualize: False
  sankey:
    do_visualize: True
    plotter_args:
      slice_dict:
        t: 2050
      split_flows_by: 'Stock Type'
      color_scheme: 'blueish'
      flow_color: 'hsl(230,20,70)'
      exclude_processes:
        - "sysenv"
      exclude_flows: [ ]
  extrapolation:
    do_visualize: True
  carbonation:
    do_visualize: True

export:
  do_export: True
  path: 'data/cement/output/export'
  pickle:
    do_export: True
  csv:
    do_export: True
  iamc:
    do_export: True
  assumptions:
    do_export: True
  docs:
    do_export: True
    path: 'docs/cement'
