# general config
model: 'cement'

# data sources
madrat_output_path: '../madrat_wd/output'
input_data_path: '../simson_data/data/cement/output'
input_data_version: 'rev0_h12_c378de4d_mfa'
scenarios_path: 'config/scenarios'

model_switches:
  scenario: 'SSP2'
  mode: 'base' # can be "base", "carbon_flow"
  stock_extrapolation_class_name: 'LogSigmoidExtrapolation'
  lifetime_model_name: 'LogNormalLifetime'
  parameter_extrapolation:
    clinker_ratio: 'ConstantExtrapolation'
    use_lifetime_mean: 'ConstantExtrapolation'

# visualization
visualization:
  do_visualize: True
  consumption:
    do_visualize: True
  use_stock:
    do_visualize: True
    over_gdp: True
    per_capita: True
  eol_stock:
    do_visualize: True
    over_gdp: False
    per_capita: False
  prod_clinker:
    do_visualize: False
  prod_cement:
    do_visualize: True
  prod_product:
    do_visualize: False
  sankey:
    do_visualize: True
    slice_dict:
      t: 2050
    split_flows_by: 'Stock Type'
    color_scheme: 'blueish'
    flow_color: 'hsl(230,20,70)'
    exclude_processes:
      - "sysenv"
    exclude_flows: [ ]
  extrapolation:
    do_visualize: False
  carbonation:
    do_visualize: False
  do_show_figs: True
  do_save_figs: False
  plotting_engine: 'plotly'

# data export
output_path: 'data/cement/output'
docs_path: 'docs/cement'
do_export:
  pickle: True
  csv: True
  docs: True
