# general config
model_class: 'cement'

# data sources
input_data_path: '../simson_data/data/cement/output'

# model customization
customization:
  stock_extrapolation_class_name: 'LogSigmoidExtrapolation'
  lifetime_model_name: 'LogNormalLifetime'

# visualization
visualization:
  do_visualize: True
  use_stock:
    do_visualize: True
    over_gdp: True
    per_capita: True
  eol_stock:
    do_visualize: True
    over_gdp: False
    per_capita: False
  clinker_production:
    do_visualize: False
  cement_production:
    do_visualize: True
  concrete_production:
    do_visualize: False
  sankey:
    do_visualize: True
    slice_dict:
      t: 2050
    split_flows_by: 'Stock Type'
    color_scheme: 'blueish'
    flow_color: 'hsl(230,20,70)'
    exclude_processes:
      - "sysenv"
    exclude_flows: [ ]
  extrapolation:
    do_visualize: True
  do_show_figs: True
  do_save_figs: False
  plotting_engine: 'plotly'

# data export
output_path: 'data/cement/output'
docs_path: 'docs/cement'
do_export:
  pickle: True
  csv: True
  docs: True
