model: 'plastics'

input:
  madrat_output_path: '../../madrat/output'
  input_data_path: '../simson_data/data/plastics/output'
  input_data_version: 'rev0backcast_trade_h12_d499589e_mfa'
  scenarios_path: 'config/scenarios'

model_switches:
  scenario: 'SSP2'
  stock_extrapolation_class_name: 'SigmoidExtrapolation'
  regress_over: 'loggdppc_time_weighted_sum'
  lifetime_model_name: 'LogNormalLifetime'
  do_stock_extrapolation_by_category: True

visualization:
  do_visualize: True
  do_show_figs: True
  do_save_figs: True
  figures_path: 'data/plastics/output/figures'
  use_stock:
    do_visualize: True
    over_gdp: False
    accumulate_gdp: True
    per_capita: True
  production:
    do_visualize: True
  extrapolation:
    do_visualize: True
  sankey:
    do_visualize: True
    plotter_args:
      slice_dict:
        t: 2020
      exclude_processes:
        - "sysenv"
        #- "waste_market"
        #- "primary_market"
        #- "intermediate_market"
        #- "good_market"
      exclude_flows: [ ]
  flows:
    do_visualize: True

export:
  path: 'data/plastics/output/export'
  pickle:
    do_export: True
  pickle:
    do_export: True
  csv:
    do_export: True
  iamc:
    do_export: True
  docs:
    do_export: True
    path: 'docs/plastics'
  assumptions:
    do_export: True
