model: 'plastics'

input:
  madrat_output_path: '../../madrat/output'
  force_extract_tgz: FALSE
  input_data_path: '../remind_mfa_data'
  input_data_version: 'rev0clean_up_h12_944165e0_mfa'
  scenarios_path: 'config/scenarios'

model_switches:
  scenario: 'SSP2'
  stock_extrapolation_class_name: 'LogisticExtrapolation'
  regress_over: 'loggdppc_time_weighted_sum'
  lifetime_model_name: 'LogNormalLifetime'
  do_stock_extrapolation_by_category: True
  parameter_extrapolation:
    collection_rate: LinearToTargetExtrapolation
    incineration_rate: LinearToTargetExtrapolation
    mechanical_recycling_rate: LinearToTargetExtrapolation
    chemical_recycling_rate: LinearToTargetExtrapolation
    bio_production_rate: LinearToTargetExtrapolation
    daccu_production_rate: LinearToTargetExtrapolation
    emission_capture_rate: ConstantExtrapolation

visualization:
  do_visualize: False
  do_show_figs: True
  do_save_figs: True
  figures_path: 'data/plastics/output/figures'
  use_stock:
    do_visualize: False
    over_gdp: False
    accumulate_gdp: True
    per_capita: True
  production:
    do_visualize: False
  extrapolation:
    do_visualize: False
  sankey:
    do_visualize: True
    plotter_args:
      slice_dict:
        t: 2020
        r: 'EUR'
      exclude_processes:
        - "sysenv"
        #- "waste_market"
        #- "primary_market"
        #- "intermediate_market"
        #- "good_market"
      exclude_flows: [ ]
  flows:
    do_visualize: True

export:
  do_export: True
  path: 'data/plastics/output/export'
  pickle:
    do_export: True
  csv:
    do_export: True
  iamc:
    do_export: True
  assumptions:
    do_export: True
  docs:
    do_export: True
    path: 'docs/plastics'
