# general config
model: 'plastics'

# data sources
input_data_path: '../simson_data/data/plastics/output'
scenarios_path: 'config/scenarios'

# model customization
customization:
  scenario: 'SSP2'
  stock_extrapolation_class_name: 'SigmoidExtrapolation'
  regress_over: 'loggdppc_time_weighted_sum'
  lifetime_model_name: 'LogNormalLifetime'
  do_stock_extrapolation_by_category: True

# visualization
visualization:
  do_visualize: False
  use_stock:
    do_visualize: True
    over_gdp: True
    acc: True
    per_capita: True
  production:
    do_visualize: True
  extrapolation:
    do_visualize: True
  sankey:
    do_visualize: True
    slice_dict:
      t: 2020
    exclude_processes:
      - "sysenv"
      #- "waste_market"
      #- "primary_market"
      #- "intermediate_market"
      #- "good_market"
    exclude_flows: [ ]
  flows:
    do_visualize: True
  do_show_figs: True
  do_save_figs: False

# data export
output_path: 'data/plastics/output'
docs_path: 'docs/plastics'
do_export:
  pickle: False
  csv: False
  iamc: False
  docs: True
  assumptions: False
