# general config
model_class: 'plastics'

# data sources
input_data_path: '../simson_data/data/plastics/output'

# model customization
customization:
  stock_extrapolation_class_name: 'SigmoidExtrapolation'
  regress_over: 'loggdppc_time_weighted_sum'
  lifetime_model_name: 'LogNormalLifetime'
  do_stock_extrapolation_by_category: True

# visualization
visualization:
  do_visualize: True
  use_stock:
    do_visualize: False
    # options: 'time', 'gdppc'
    # over: 'gdppc'
    over_gdp: False
    acc: True
    per_capita: True
  production:
    do_visualize: True
  extrapolation:
    do_visualize: True
  sankey:
    do_visualize: False
    slice_dict:
      t: 2020
    exclude_processes:
      - "sysenv"
      #- "waste_market"
      #- "primary_market"
      #- "intermediate_market"
      #- "good_market"
    exclude_flows: [ ]
  flows:
    do_visualize: True
  do_show_figs: True
  do_save_figs: True

# data export
output_path: 'data/plastics/output'
do_export:
  pickle: False
  csv: False
  iamc: False
