# general config
model_class: 'plastics'

# data sources
input_data_path: '../simson_data/data/plastics/output'

# model customization
model_switches:
  stock_extrapolation_class_name: 'LogSigmoidExtrapolation'
  lifetime_model_name: 'NormalLifetime'
  do_stock_extrapolation_by_category: True

# visualization
visualization:
  use_stock:
    do_visualize: True
    # options: 'time', 'gdppc'
    over: 'gdppc'
    per_capita: True
  production:
    do_visualize: True
  sankey:
    do_visualize: True
    slice_dict:
      t: 2020
    exclude_processes:
      - "sysenv"
    exclude_flows: [ ]
  do_show_figs: True
  do_save_figs: False

# data export
output_path: 'data/plastics/output'
do_export:
  pickle: False
  csv: True
